---
title: "Physiology"
author: "Debbie Leung"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up
```{r}
# install.packages(c("ggplot2", "dplyr", "tidyr"))
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
mydata <- read.csv("physiology_data.csv", stringsAsFactors = FALSE) %>% na_if("")
df <- data.frame(mydata)
```

## Summary Statistics

```{r}
summary(df)
```
```{r}
str(df)
```

## Exploratory Figures

### Heart Rate
```{r}
# Compare box and violin plots
hr <- df %>% drop_na(heart_rate) # drop NA for heart rate
ggplot(data = hr, aes(x = heating_rate, y = heart_rate, fill=time_point)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_jitter() + ggtitle("A boxplot of heart rate against heating rates") 
```
```{r}
ggplot(data = hr, aes(x = heating_rate, y = heart_rate, , fill=time_point)) + geom_violin() + geom_jitter()
```

### Osmolality


### Weight Loss

### Thermal Equilibrium

### Random Variables

## Publication Figures

###
