---
title: "Physiology_Publication"
author: "Debbie Leung"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up
```{r}
# install.packages(c("ggplot2", "dplyr", "tidyr", "gridExtra", "cowplot", "lattice", "ggsci", "ggpubr"))
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(cowplot)
library(lattice)
library(ggsci)
library(ggpubr)
```

```{r, echo=FALSE}
mydata <- read.csv("physiology_cleaned.csv", stringsAsFactors = FALSE) %>% na_if("")
df <- data.frame(mydata)
```

## Heart Rate

```{r}
# Plot with both high and low tide
hr <- df %>% drop_na(heart_rate) # drop NA for heart rate, simultaneously filtering for H and L only

ggplot(data = hr, aes(x = time_point, y = heart_rate, fill=heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point(aes(color=tidal_height), alpha=0.7) + labs(x="time point", y="heart rate (hertz)", fill="warming rate") + theme_bw() + scale_fill_npg()
```

Comments:
1. black dot in T0 for C_air
2. how to use geom_point() to get points aligned for each heating rate
3. follow npg color palette of Nature for the tidal points

```{r}
compare_means(heart_rate ~ heating_rate, data = mydata, method = "anova")
```

```{r}
# Two separate plots of high and low tide side-by-side
hr <- df %>% drop_na(heart_rate) # drop NA for heart rate, simultaneously filtering for H and L only
high <- subset(hr, tidal_height == "H")
low <- subset(hr, tidal_height == "L")
#my_comparisons <- list( c("T0", "T1"), c("T0", "T2"), c("T1", "T2"))

ggplot(data = hr, aes(x = time_point, y = heart_rate, fill = heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point() + facet_wrap(~tidal_height, labeller = labeller(tidal_height = c("H" = "Tidal Height (TH): High", "L" = "Tidal Height (TH): Low"))) + labs(x="Time Point (TP)", y="Heart Rate (Hertz)", fill="Warming Rate (WR)") + theme_bw() + scale_fill_npg() #+ annotate("text", x = 2, y = 0.6, label = "WR: p=0.000461, TP: p=010996,", size = 3) #+ annotate("text", x = 2, y = 0.58, label = "WR*TH: p=0.014742", size = 3)

```

## Osmolality

```{r}
# Two separate plots of high and low tide side-by-side
osmo <- df %>% drop_na(osmolality) 
high <- subset(osmo, tidal_height == "H")
low <- subset(osmo, tidal_height == "L")

ggplot(data = osmo, aes(x = time_point, y = osmolality, fill = heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point() + facet_wrap(~tidal_height, labeller = labeller(tidal_height = c("H" = "Tidal Height (TH): High", "L" = "Tidal Height (TH): Low"))) + labs(x="Time Point (TP)", y= expression("Osmolality (mOsm"~kg^-1~")"), fill="Warming Rate (WR)") + theme_bw() + scale_fill_npg()

```

## Weight Loss

```{r}
# Two separate plots of high and low tide side-by-side
wloss <- df %>% drop_na(weight_loss_percent)
high <- subset(wloss, tidal_height == "H")
low <- subset(wloss, tidal_height == "L")

ggplot(data = wloss, aes(x = time_point, y = weight_loss_percent, fill = heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point() + facet_wrap(~tidal_height, labeller = labeller(tidal_height = c("H" = "Tidal Height (TH): High", "L" = "Tidal Height (TH): Low"))) + labs(x="Time Point (TP)", y="Weight Loss Percentage", fill="Warming Rate (WR)") + theme_bw() + scale_fill_npg() #+ annotate("text", x = 2, y = 3.5, label = "WR: p=3.3e-10, TP: p=0.000118", size = 3)
```

## Thermal Equilibrium

```{r avgtemp}
# Two separate plots of high and low tide side-by-side
tempavg <- df %>% drop_na(average_temp)
high <- subset(tempavg, tidal_height == "H")
low <- subset(tempavg, tidal_height == "L")

ggplot(data = tempavg, aes(x = time_point, y = average_temp, fill = heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point() + facet_wrap(~tidal_height, labeller = labeller(tidal_height = c("H" = "Tidal Height (TH): High", "L" = "Tidal Height (TH): Low"))) + labs(x="Time Point (TP)", y= "Average Body Temperature (°C)", fill="Warming Rate (WR)") + theme_bw() + scale_fill_npg() #+ annotate("text", x = 2, y = 41, label = "WR: p<2e-16, TP: p=0.00228", size = 3)

```
```{r tempsd}
# Two separate plots of high and low tide side-by-side
tempsd <- df %>% drop_na(temp_sd)
high <- subset(tempsd, tidal_height == "H")
low <- subset(tempsd, tidal_height == "L")

ggplot(data = tempsd, aes(x = time_point, y = temp_sd, fill = heating_rate)) + stat_boxplot(geom = "errorbar") + geom_boxplot() + geom_point() + facet_wrap(~tidal_height, labeller = labeller(tidal_height = c("H" = "Tidal Height (TH): High", "L" = "Tidal Height (TH): Low"))) + labs(x="Time Point (TP)", y= "Body Temperature Standard Deviation (°C)", fill="Warming Rate (WR)") + theme_bw() + scale_fill_npg() + annotate("text", x = 2, y = 1.8, label = "WR: p=4.2e-16, WR*TH: p=0.0452", size = 3) + annotate("text", x = 2, y = 1.73, label = "WR*TH*TP: p=0.0255", size = 3)
```

